# Generated by Django 3.0.9 on 2020-08-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название экскурсии')),
                ('description_short', models.CharField(max_length=500, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image', verbose_name='Фотографии экскурсии')),
                ('image_number', models.PositiveSmallIntegerField(verbose_name='Номер картинки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='places.Place', verbose_name='название экскурсии')),
            ],
        ),
    ]
