# Generated by Django 3.0.9 on 2020-08-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['place', 'image_number'], 'verbose_name': 'Изображение экскурсии', 'verbose_name_plural': 'Изображения экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
    ]
